name: Generate snake animation

on:
  push:
    branches:
      - main

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: platane/snk@master
        with:
          github_user: 'everton-nfs' 
          svg_out: 'output/snake.svg'
          clean: true 
